export enum DomainExceptionCodes {
  NOT_FOUND = 'NOT_FOUND',
  ALREADY_IN_USE = 'ALREADY_IN_USE',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL = 'INTERNAL',
  INVALID_PARAM = 'INVALID_PARAM',
}
