version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    container_name: perseu-redis
    ports:
      - 6379:6379
  
  rabbitmq:
    image: rabbitmq:3.9-management
    restart: always
    container_name: perseu-rabbitmq
    ports:
      - 5672:5672

  node:
    image: rafaelpapastamatiou/node-perseu
    container_name: perseu-node
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - rabbitmq
    command: >
      ./wait-for-it.sh perseu-rabbitmq:5672 -- yarn dev:docker