version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    container_name: perseu-redis
    ports:
      - 6379:6379
  
  rabbitmq:
    image: rabbitmq:3.9-management
    restart: always
    container_name: perseu-rabbitmq
    ports:
      - 5672:5672